In [ ]:
import numpy as np
import numpy.linalg as LA
from sympy import *

In [ ]:
A = np.array([
    [-6,4,0,9],
    [-3,0,1,6],
    [-1,-2,1,0],
    [-4,4,0,7]
])

I = np.identity(4)

# 1. Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = LA.eig( A )

print(eigenvalues)
print(eigenvectors)

# print(I)


for eigenvalue in eigenvalues:
  eigen_matrix = eigenvalue * I
  eigen_matrix = A * eigen_matrix 

  print('before rref:\n', eigen_matrix)

  eigen_matrix_rref, pivots = Matrix(eigen_matrix).rref()
  print('after rref:\n', eigen_matrix)

  print(pivots)
  # once the pivot columns are determined, 
  # we can determine the general solution to A - Lambda_I = 0 for each lambda. But how?


[ 5.  1. -2. -2.]
[[-0.63245553  0.26261287 -0.86819922  0.39602146]
 [-0.31622777 -0.13130643 -0.078836   -0.70170179]
 [ 0.31622777 -0.91914503 -0.34195707 -0.33579404]
 [-0.63245553  0.26261287 -0.3508281   0.487877  ]]
before rref:
 [[-30.   0.   0.   0.]
 [ -0.   0.   0.   0.]
 [ -0.  -0.   5.   0.]
 [ -0.   0.   0.  35.]]
after rref:
 [[-30.   0.   0.   0.]
 [ -0.   0.   0.   0.]
 [ -0.  -0.   5.   0.]
 [ -0.   0.   0.  35.]]
(0, 2, 3)
before rref:
 [[-6.  0.  0.  0.]
 [-0.  0.  0.  0.]
 [-0. -0.  1.  0.]
 [-0.  0.  0.  7.]]
after rref:
 [[-6.  0.  0.  0.]
 [-0.  0.  0.  0.]
 [-0. -0.  1.  0.]
 [-0.  0.  0.  7.]]
(0, 2, 3)
before rref:
 [[ 12.  -0.  -0.  -0.]
 [  0.  -0.  -0.  -0.]
 [  0.   0.  -2.  -0.]
 [  0.  -0.  -0. -14.]]
after rref:
 [[ 12.  -0.  -0.  -0.]
 [  0.  -0.  -0.  -0.]
 [  0.   0.  -2.  -0.]
 [  0.  -0.  -0. -14.]]
(0, 2, 3)
before rref:
 [[ 12.  -0.  -0.  -0.]
 [  0.  -0.  -0.  -0.]
 [  0.   0.  -2.  -0.]
 [  0.  -0.  -0. -14.]]
after rref:
 [[ 12.  -0.  -0.  -0

In [ ]:
# Q2

A = [
    [-6,4,0,9],
    [-3,0,1,6],
    [-1,-2,1,0],
    [-4,4,0,7]
]

I = np.identity(4)
# 1. Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = LA.eig( A )

basis_vectors = []
for eigenvalue in eigenvalues:
  # 2. Set up augmented  characteristic equation 
  eigen_matrix = eigenvalue * I
  eigen_matrix = A * eigen_matrix

  # convert to row echelon form, find pivots
  eigen_matrix_rref, pivots = Matrix(eigen_matrix).rref()

  # from pivot columns, determine basis vector
  basis_vector = solve ( eigen_matrix_rref, pivots )
  basis_vectors.append( basis_vectors )

print('ans: ', basis_vectors)

ans:  [[...], [...], [...], [...]]
